server:
  port: 8082

spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - prod

  build.version: 3.0

  cards:
    message: "Welcome to MiniBank loans related Local APIs "
    contactDetails:
      name: "Nirakar Asha - Developer"
      email: "nirakar.asha@gmail.com"
    onCallSupport:
      - (011) 222-1234
