build.version: 3.0

accounts:
  message: "Welcome to MiniBank accounts related Local APIs "
  contactDetails:
    name: "Nirakar Asha - Developer"
    email: "nirakar.asha@gmail.com"
  onCallSupport:
    - (011) 222-1234
