server:
  port: 8888

encrypt:
  key: "23DRF879JKLA0987BASWQ674FTRYIQ3091F9"

spring:
  application.name: configserver
  profiles:
    active:
#      - native
      - git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/anirakar/microservice-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations:
#            - "classpath:/config"
